### ISSUE TITLE
xunit reporter does not exist with version 2.2.0

### ISSUE THREAD

**Issue by MaxK4Code** [DevExpress/testcafe-reporter-xunit#17]
**issue:** Bug (maybe)

**background:**
Some days ago testcafe-reporter-xunit was shipped with testcafe in version 2.1.0. Everything worked and was awesome. ;)
We use the current version of testcafe (1.17.1).

After your new release of 2.2.0 a new developer in our team installed testcafe and got this version from npm.
In testcafe there is a dependency of _^2.1.0_ for the reporter.

If we run testcafe we get the following error:
`The "xunit" reporter does not exist. Check the reporter parameter for errors.`

(checked on multiple devices and projects)

**workaround:**
We install the version 2.1.0 of the reporter and it works.

Oh oh?

Best regards
Max

**Comment by OmerDavid2312** [comment]
Hey
I have the same problem and can not run my testcafe in all project
how did you reduce the version from 2.2 to 2.1.0?
because it sub dependency of testcafe

**Comment by MaxK4Code** [comment]
Delete the reporter from node_modules and install it on your own:
`npm i -D testcafe-reporter-xunit@2.1.0`

**Comment by OmerDavid2312** [comment]
and them testcafe will use his sub depanacy ? xunit reporter ?

**Comment by MaxK4Code** [comment]
> and them testcafe will use his sub depanacy ? xunit reporter ?

yes, npm uses the packages in your node_modules folder, when you start testcafe from there.
when you use a global installation of testcafe then you have to install the reporter as a global package too

**Comment by OmerDavid2312** [comment]
Hey, 
Its looks like they fixed it on v2.1.0 and its works now,
is it work for you as well?
Can you share maybe share advice on how to prevent this problem, I had one day without automation tests because of it which is really important ..
thank again !

**Comment by MaxK4Code** [comment]
Hey
Yeah, it is **fixed in version 2.2.1**.
Works as before.
There is no advice to prevent those problems. If the npm-publisher pushes a nonworking library and you install this version you will get such problems.

Sh.. happens ;-)
