### ISSUE TITLE
Using absolute path for the `file` attribute, CircleCi expects relative path 

### ISSUE THREAD

**Issue by rob4629** [DevExpress/testcafe-reporter-xunit#23]
It seems like we're writing the absolute path for the `file` attribute, rather than a relative path (which CircleCi expects).

```
Error autodetecting timing type, falling back to weighting by name. Autodetect no matching filename or classname.  If file names are used, double check paths for absolute vs relative.
Example input file: "tests/payments/promotions/some_test.js"
Example file from timings: "/home/circleci/regression-qaa/tests/payments/promotions/ppmu/some_other_test.js"
```

I'm not sure how many people this is affecting... but is there an easy way for us to fix/change/overwrite this?

**Comment by AlexKamaev** [comment]
It's easy to change an absolute path to a relative one. However, I am afraid this will be a breaking change. The best option would be passing some arguments to the reporter, but we do not have such a feature and do not have plans to implement it.

I suggest that you process your resulting xml file to update your file attributes on your side.
