### ISSUE TITLE
File field in testcase

### ISSUE THREAD

**Issue by AGrigorii** [DevExpress/testcafe-reporter-xunit#24]
Привет!
Для корректного отображения в gitlab переписываю следующим образом репорт: 
```ts
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const cwd = process.cwd();

const report = readFileSync(resolve(cwd, 'testcafe/reports/report.xml'), { encoding: 'utf-8' });
const fixed = report.replace(new RegExp(cwd, 'g'), () => '');

writeFileSync(resolve(cwd, 'testcafe/reports/report.xml'), fixed);
```
тем самым превращаю пути в относительные относительно репозитория:
![image](https://user-images.githubusercontent.com/44318220/194079945-63892b94-a0e2-4d88-94d0-41289c44e711.png)

Подскажите, пожалуйста, есть ли стопперы к тому, что я создам вам в пакет пиар с этими правками?

**Comment by rob4629** [comment]
Это выглядит хорошо, я проведу несколько тестов, чтобы подтвердить. Спасибо

**Comment by AlexKamaev** [comment]
This approach can be used as a workaround, but I'm afraid we cannot accept this kind of changes. We did not come to the conclusion regarding the `file` field in `testcafe-reporter-xunit` yet.

**Comment by AGrigorii** [comment]
Just to let you, [jest junit reporter](https://www.npmjs.com/package/jest-junit) prints relative to project paths for such attributes by default. I have no idea, what is the benefit absolute path to be here.

**Comment by AlexKamaev** [comment]
Thank you for sharing this information. We'll take it into account.

**Comment by rob4629** [comment]
> Thank you for sharing this information. We'll take it into account.

Does that mean we can re-open this issue? Honestly, having the full path does nothing to solve the problem of why this attribute was requested in the first place

**Comment by AlexKamaev** [comment]
This issue only suggests a workaround, so we don't need to reopen it. However, in the `testcafe-reporter-xunit` repo, we can accept a PR with changing an absolute path to a relative one.

**Comment by AGrigorii** [comment]
We'd like to contribute by that) Let us do

**Comment by AlexKamaev** [comment]
@AGrigorii
Please take into account that we would accept changes only in the `testcafe-reporter-xunit` module. We'd prefer not to modify the TestCafe code.
