### ISSUE TITLE
Add clarification for xunit reporter format

### ISSUE THREAD

**Issue by chrish619** [DevExpress/testcafe-reporter-xunit#5]
Issue: Documentation

Steps to Replicate:
* being silly, and not understanding there's a difference between XUnit, and a xUnit.Net format (@chrish619)
* Add a "Publish Test Result" step to Azure DevOps / vsts CI Build - setting XUnit as the source format - (but really this means xUnit.Net format)
* ```Total test results: 0.``` logged in `system.debug` build log

Possible resolutions?
* Read documentation _better_ - @chrish619
* Please add a small FAQ, N.B., or 'Gotcha' to the `readme.md` - to prevent other developer confusion?
* An Azure DevOps/VSTS integration guide, and mention the `JUnit` format as being a solution?

Or, maybe this "Issue" will be enough 😄

**Comment by AndreyBelym** [comment]
Thank you for your feedback. Yes, there is a subtle difference between different meanings of the `xunit` word: the *x*Unit family of formats derived from the JUnit format and the specific `xUnit.net` format. This plugin uses the first meaning of `xunit`. I think we should add a clarification about this in `README.md`.

**Comment by agentHoover** [comment]
Any chance you are planning to add support for the xunit.net format?  That would be more helpful than just documenting that it is not supported.  :)

**Comment by AndreyBelym** [comment]
@agentHoover it requires more works that just documenting that Xunit.net is not supported by this reporter. By the way, if we implement Xunit.net support, we will create a separate package to preserve backward compatibility. So if you write a Xunit.net reporter, we can consider using your implementation and promote it in the [Plugins](https://github.com/DevExpress/testcafe#plugins) section in the TestCafe's documentation :smile:
