### ISSUE TITLE
How can I write output to a file using the reporter method

### ISSUE THREAD

**Issue by kweij** [DevExpress/testcafe-reporter-xunit#6]
Documentation state the following usage:

```
testCafe
    .createRunner()
    .src('path/to/test/file.js')
    .browsers('chrome')
    .reporter('xunit') // <-
    .run();
```

But how can I specify a filename to write out the results? Setting the reporter like this only formats the console.logged output, but I want it in a file.

Thanks in advance

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. This issue looks like a question that would be best [asked on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

You can use the following approaches to redirect the reporter's output to a file:
```js
testCafe
    .createRunner()
    .src('path/to/test/file.js')
    .browsers('chrome')
    .reporter('xunit', 'report.xml')
    .run();
```
```js
testCafe
    .createRunner()
    .src('path/to/test/file.js')
    .browsers('chrome')
    .reporter({ name: 'xunit', output: 'report.xml' })
    .run();
```

**Comment by kweij** [comment]
Thanks you so much for the quick response. And indeed, I should've posted this on StackOverflow.
